// Generated by CoffeeScript 1.10.0
(function() {
  var findTerm, node, traverse;

  traverse = function(node) {
    return {
      each: function(fn) {
        var results1;
        fn(node);
        node = node.firstChild;
        results1 = [];
        while (node) {
          traverse(node).each(fn);
          results1.push(node.nextSibling);
        }
        return results1;
      }
    };
  };

  node = function(node) {
    var root;
    root = this;
    return {
      hasTerm: function(term) {
        return node.innerText.indexOf(term !== -1);
      }
    };
  };

  findTerm = function(term) {
    var results, root;
    root = this;
    root.results = [];
    results = root.results;
    root.src = void 0;
    return {
      "in": function(node) {
        var src;
        src = node;
        if (node(node).hasTerm(term)) {
          results.push(node);
        }
        return root;
      },
      x: function(times) {
        console.log("times");
        return results;
      }
    };
  };

}).call(this);
