// Generated by CoffeeScript 1.10.0
(function() {
  var findTerm;

  findTerm = function(term) {
    var root;
    root = this;
    return {
      "in": function(node) {
        return console.log("node");
      },
      x: function(times) {
        return console.log("times");
      }
    };
  };

}).call(this);
